

email:
    mailgun:
        api_url         : 'https://api.mailgun.net/v2'
        email_from      : 'Journal Digest <noreply@journaldigest.mailgun.org>'
        reply_to        : 'Erica Lenton <Erica.Lenton@albertahealthservices.ca>'
        list_domain     : 'journaldigest.mailgun.org'


