
feeds:
    -   name                : 'Journal of Clinical Oncology'
        url                 : 'http://jco.ascopubs.org/rss/current.xml'
        list_name           : 'dev-test'

        date_format         : '%Y-%m-%dT%H:%M:%S'
        time_zone           : 'MST'
        date_strip          : [0, 6]
        normalize_class     : PrismFeedNormalizer

    -   name                : 'ScienceDirect Publication: The Lancet Oncology'
        url                 : 'http://rss.sciencedirect.com/publication/science/6645'
        list_name           : 'dev-test'

        date_format         : '%Y-%m-%dT%H:%M:%SZ'
        time_zone           : 'UTC'
        date_strip          : []
        normalize_class     : LancetFeedNormalizer

    -   name                : 'Nature Reviews Clinical Oncology'
        url                 : 'http://feeds.nature.com/nrclinonc/rss/current?format=xml'
        list_name           : 'dev-test'

        date_format         : '%Y-%m-%d'
        time_zone           : 'UTC'
        date_strip          : []
        normalize_class     : PrismFeedNormalizer
 
